---
joint_state_estimator:
  ros__parameters:
    type: linear_feedback_controller/JointStateEstimator
    state_interfaces:
    - fer_joint1/position
    - fer_joint2/position
    - fer_joint3/position
    - fer_joint4/position
    - fer_joint5/position
    - fer_joint6/position
    - fer_joint7/position
    - fer_joint1/velocity
    - fer_joint2/velocity
    - fer_joint3/velocity
    - fer_joint4/velocity
    - fer_joint5/velocity
    - fer_joint6/velocity
    - fer_joint7/velocity
    - fer_joint1/effort
    - fer_joint2/effort
    - fer_joint3/effort
    - fer_joint4/effort
    - fer_joint5/effort
    - fer_joint6/effort
    - fer_joint7/effort
    command_interfaces:
    - linear_feedback_controller/fer_joint1/position
    - linear_feedback_controller/fer_joint2/position
    - linear_feedback_controller/fer_joint3/position
    - linear_feedback_controller/fer_joint4/position
    - linear_feedback_controller/fer_joint5/position
    - linear_feedback_controller/fer_joint6/position
    - linear_feedback_controller/fer_joint7/position
    - linear_feedback_controller/fer_joint1/velocity
    - linear_feedback_controller/fer_joint2/velocity
    - linear_feedback_controller/fer_joint3/velocity
    - linear_feedback_controller/fer_joint4/velocity
    - linear_feedback_controller/fer_joint5/velocity
    - linear_feedback_controller/fer_joint6/velocity
    - linear_feedback_controller/fer_joint7/velocity
    - linear_feedback_controller/fer_joint1/effort
    - linear_feedback_controller/fer_joint2/effort
    - linear_feedback_controller/fer_joint3/effort
    - linear_feedback_controller/fer_joint4/effort
    - linear_feedback_controller/fer_joint5/effort
    - linear_feedback_controller/fer_joint6/effort
    - linear_feedback_controller/fer_joint7/effort

linear_feedback_controller:
  ros__parameters:
    type: linear_feedback_controller/LinearFeedbackController
    moving_joint_names:
    - fer_joint1
    - fer_joint2
    - fer_joint3
    - fer_joint4
    - fer_joint5
    - fer_joint6
    - fer_joint7
    fer_joint1:
      p: 1000.0
      d: 5.0
    fer_joint2:
      p: 1000.0
      d: 5.0
    fer_joint3:
      p: 1000.0
      d: 5.0
    fer_joint4:
      p: 1000.0
      d: 2.0
    fer_joint5:
      p: 20.0
      d: 2.0
    fer_joint6:
      p: 10.0
      d: 2.0
    fer_joint7:
      p: 5.0
      d: 1.0
    chainable_controller:
      command_interfaces:
      - fer_joint1/effort
      - fer_joint2/effort
      - fer_joint3/effort
      - fer_joint4/effort
      - fer_joint5/effort
      - fer_joint6/effort
      - fer_joint7/effort
      reference_prefix: ''
    joint_velocity_filter_coefficient: 0.9
    pd_to_lf_transition_duration: 0.1
    remove_gravity_compensation_effort: true
    robot_has_free_flyer: false
